### ISSUE TITLE
Generate based on subprogram (procedure/function) inside a package?

### ISSUE THREAD

**Issue by mortenbra** [oddgen/oddgen#26]
The tutorial shows how you can adjust the object types that show in the treeview under the generator, such as Table and View. I assume all "top-level" object types in Oracle such as Indexes, Sequences, Triggers, Packages, Types, etc. are supported via the get_object_types function.

However, it would also be useful to generate code based on a specific subprogram (function or procedure) within a package, for example to generate a block of code for calling the selected subprogram. That would require the Oddgen plugin to display a list of packages that could be expanded to show the subprograms in that package (basically populated with something like "select procedure_name from all_procedures where owner = 'OWNER_NAME' and object_name = 'PACKAGE_NAME'"), allow the user to mark one or more subprograms in a given package, and of course Oddgen would also have to pass along the selected subprogram into the generate() procedure.

Is this possible? Perhaps with some generic "sub_object_name" extension of the existing API?

**Comment by PhilippSalvisberg** [comment]
Good points. I have to admit that I'm currently not very happy with the missing flexibility of the navigator tree. One point is addressed in #10  but there are others like calling generator from a folder and the point you addressing. Something like "extend the API to support custom trees". I see the "sub_object_name" as a subset of custom tree support. I've opened an enhancement issue #28 for that purpose and will treat this issue as a question.

However, for your problem I see currently two options:

a) Define a parameter see [issue_26a](https://gist.github.com/PhilippSalvisberg/68d50c5d5fc604d81a1c8ccb7ac95d0f#file-issue_26a-sql)
b) Construct an artificial object name by concatenating object_name and procedure. See [issue_26b](https://gist.github.com/PhilippSalvisberg/68d50c5d5fc604d81a1c8ccb7ac95d0f#file-issue_26b-sql)

Option a) has the drawback, that this works just for a single function/procedure, no real multi-selection support.

Option b) has the drawback, that the list in the navigator tree could become brutally long and you have to parse the artificial object_name to get the real object_name and the procedure for further processing.

This clearly shows that this issue should be addressed.

BTW: while writing an example for an option a) generator I've stumbled over issue #27 which is fixed by now. I'll release a new version of oddgen soon. In the meantime if you want to experiment with option a) you have to use in_object_type instead of in_object_name and vice versa in the get_lov function.

**Comment by PhilippSalvisberg** [comment]
v0.2.2 is released and I've changed the links for option a) and b). Using Gist instead of attached files.
