### ISSUE TITLE
How to enable logging? / PLS-00103 when connecting from Windows to Oracle Database Server 10.2.0.5

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#3]
I'm receiving an error while trying out the teplsql_hello_world example
(PLS-00103: Encountered the symbol "" when expecting one of the following: ...)

I'd like to see more information regarding how this error was generated.
eg the java error stack.

note - the pl/sql that is shown in the Logs works from sql*developer worksheet.

**Comment by PhilippSalvisberg** [comment]
Could you please add the following information:
1. what have you installed exactly on your database regarding the hello world example (e.g. the package spec, package body, grants to public)
2. which step caused the problem in the oddgen navigator (e.g. retrieving generators, retrieving object types (table/views), retrieving object names (table names, view names), generating to worksheet for a chosen object)
3. you said that the pl/sql shown in the logs works. To which log are you referring and what was the PL/SQL statement that worked?
4. Maybe some screenshot would help too

However, if you like to enable Java logging for the oddgen extension you have to do the following:
- go to to the ...sqldeveloper/sqldeveloper/bin folder
- make a copy of the logging.conf file
- open the logging.conf file, the original content should look like this: 

```
.level=SEVERE

# Set the default logging level for the root logger
#oracle.level = INFO

# --- ConsoleHandler ---
# Override of global logging level
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
oracle.dbtools.logging.LogPaneHandler.level=ALL
oracle.ide.log.QueuedLoggingHandler.level=OFF
```
- change the content of logging.conf to

```
#handler for console only (will be shown in Messages pane within SQL Developer)
handlers=java.util.logging.ConsoleHandler

# Default global logging level. 
.level=SEVERE

# Loggers 
oracle.level=FINE
org.oddgen.level=ALL
com.jcabi=ALL

# --- ConsoleHandler --- 
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s %3$s: %5$s%n
```
- save the file
- restart SQL Developer

Successful executed SQL statements may be truncated in the log, but unsuccessful statements are logged fully.

It's important to notice SQL Developer's logging pane reports the wrong class for "Source", in fact _logger_ is used instead of _source_. Usually they are the same, but oddgen uses jcabi-log and in this case they are different. - Have a look into the "Messages" tab instead. There the result is properly formatted and the source class is reported correctly.

**Comment by MikeKutz** [comment]
The modification to the logging.conf does what I wanted to accomplish.

I was going to use a different setup to validate that the problem was a bug before I discussed it (as a different "issue").

Code for procedure is from your example code
./example/teplsql/teplsql_hello_world.*

1st Setup: SQL*Developer 4.1.1.19 connecting to Oracle 10.2.0.5

"Message" shows PLS error even though code runs.
"message"
![image](https://cloud.githubusercontent.com/assets/14933751/13859042/c56d93ae-ec57-11e5-82c4-f2e18df2b23f.png)

proof that code runs
![image](https://cloud.githubusercontent.com/assets/14933751/13859055/d6ccb1c0-ec57-11e5-8954-cd58bb92fe93.png)

other setup I plan to test: SQL*Developer 4.3 connecting to Oracle 11g XE

**Comment by PhilippSalvisberg** [comment]
I'm happy that configuration of logging.conf was helpful. However, I'm a bit more concerned about the behaviour you are describing. It seems to be related to the MOS note 1399110.1. 

> PL/SQL Package Created In 10g From Java Application Is Invalid due to CR character (Doc ID 1399110.1)
> ...
> A Java JDBC application reads a text file containing PL/SQL code and submits it to a database version 10g ( 10.2.0.5 database tested).  The PL/SQL package does get created however it contains a compilation error. The same package compiles fine when the same Java program  creates it on the 11g database. ( 11.1 and 11.2 databases tested). This is not specific to the JDBC driver used by the Java program.
> ...

So the problem appears only if you are running SQL Developer under Windows and connecting against an Oracle Database Server version 10.2.0.1 to 10.2.0.5. 

I've tested oddgen successfully from SQL Developer under Windows against 9.2.0.8 and 12.1.0.4.

In order to make it work in your environment, the oddgen extension has to ensure that no CRLF line separators are used in generated PL/SQL blocks.

**Comment by PhilippSalvisberg** [comment]
Reproduced the behaviour on a 10.2.0.4 from Windows. Works perfectly from Linux or Mac OS. Here the error message shown in the worksheet as result of the generator call:

```
Failed to generate code for TABLE.EMP via OGDEMO.MINIMAL_VIEW. Got the following error: ORA-06550: line 1, column 8:
PLS-00103: Encountered the symbol "" when expecting one of the following:

   begin function package pragma procedure subtype type use
   <an identifier> <a double-quoted delimited-identifier> form
   current cursor
```

and this is the excerpt from the message log:

```
2016-03-22 21:26:07 FINE org.oddgen.sqldev.OddgenNavigatorController: Generating TABLE.EMP to worksheet...
2016-03-22 21:26:07 SEVERE org.oddgen.sqldev.dal.DatabaseGeneratorDao: DECLARE
   l_clob   CLOB;
BEGIN
   l_clob := OGDEMO.MINIMAL_VIEW.generate(
                  in_object_type => 'TABLE'
                , in_object_name => 'EMP'
             );
   ? := l_clob;
END;
Failed to generate code for TABLE.EMP via OGDEMO.MINIMAL_VIEW. Got the following error: ORA-06550: line 1, column 8:
PLS-00103: Encountered the symbol "" when expecting one of the following:

   begin function package pragma procedure subtype type use
   <an identifier> <a double-quoted delimited-identifier> form
   current cursor

2016-03-22 21:26:07 INFO org.oddgen.sqldev.dal.DatabaseGeneratorDao: #generate('DatabaseGenerator [\n  generatorOwner = "OGDEMO"\n ..223..W"\n  description = "OGDEMO.MINIMAL_VIEW"\n]'): 'Failed to generate code for TABLE.EMP via OGDEMO...241..ited-identifier> form
\n   current cursor
\n' in 3.45ms
```

SQL is not effected, just PL/SQL.
