### ISSUE TITLE
Using single quotes in parameter value causes ORA-06550 and PLS-00103

### ISSUE THREAD

**Issue by mortenbra** [oddgen/oddgen#32]
Using single quotes in parameter values, for example typing the following into the parameter input box

my_func('test_it')

causes the code generation to fail with the below error.

If I use single quotes in pairs, it works:

my_func(''test_it'')
# 

Failed to generate code for TABLE.X_INVOICE via DEVTEST.ODDGEN_TRIGGER_AND_SEQ. Got the following error: ORA-06550: line 6, column 54:
PLS-00103: Encountered the symbol "TEST_IT" when expecting one of the following:
- & = - + ; < / > at in is mod remainder not rem
  <an exponent (**)> <> or != or ~= >= <= <> and or like like2
  like4 likec between || multiset member submultiset
  The symbol "\* was inserted before "TEST_IT" to continue.

**Comment by mortenbra** [comment]
In fact, just adding a single quote to any parameter value causes generation to fail with error:

Failed to generate code for TABLE.X_INVOICE via DEVTEST.ODDGEN_TRIGGER_AND_SEQ. Got the following error: Invalid column index

**Comment by PhilippSalvisberg** [comment]
Yes, I may reproduce this error with database server generators (works with client generators). 

Dynamic PL/SQL blocks used in DatabaseGeneratorDao need to escape single quotes in parameters (no quote delimiter characters to support 9iR2).

**Comment by mortenbra** [comment]
Or better yet, pass the values as bind variables to the PL/SQL code. Using binds will improve robustness, performance and security of code.

**Comment by PhilippSalvisberg** [comment]
You're right. I thought about it, but then I have to handle dynamic number of binds... but I totally agree, it would be better to use binds in this case.

**Comment by MikeKutz** [comment]
I suggest you start using named binds.

This way you can <<calc new bind variable>> for your templates.  ;)

Then, java  bindVariable( ":var" + i, value(i) );

MK

**Comment by MikeKutz** [comment]
Oh, if you plan on supporting 9i database generators, you may want to add "oddgen properties" to set "use pre-10g quoting".

and for q'??' quoting, I recommend using a very non-common character.  eg something in greek.

$0.02

**Comment by PhilippSalvisberg** [comment]
> I suggest you start using named binds.

I'm already using binds... see getUserObjectNames in DatabaseGeneratorDao for example and I really know how to use them ;-) . However, I still have to build dynamic PL/SQL blocks  with a lot of stuff which cannot be handled by bind variables, e.g. using the package name for a generator. In the end it's a compromise to get readable code, useful debug output, good performance and other stuff like security.

> Oh, if you plan on supporting 9i database generators, you may want to add "oddgen properties"

I'm not planning to support 9iR2, I'm already doing it. No need to introduce preferences for that since the JDBC metadata delivers all I need. However, why configure stuff if I can use a syntax which is applicable for all supported versions without performance penalties? - Sorry, I do not see a value in that approach.
