### ISSUE TITLE
Structure for "donated generators"?

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#33]
Do you have a file structure in mind for actual, non example generators that are to be donated to this project?

Right now, my fork is working on this concept:
`/public/{classification}/{generator name}/README.md`

Each generator gets its own `README.md` file.
All pl/sql code can be in the same level as the `README.md` file.

This format allows generator developers to easily see "what can I implement for my generator that has been implement by others?".

For `{classification}`, that would be defined like:

| classification | description |
| --- | --- |
| dd | for Data Dictionary API (the purpose of my fork) |
| TAPI | for TAPIs |
| XAPI | for multi-table, multi-step Transactional APIs, eg package (and tables) for document library with document version numbering based on "gap free sequential numbering" |
| DBA | for DBA tools, eg "create a package for PDE that uses the modified chunk-by-rowid SQL" |
| developer | developer related tools, eg "A `stack` data type based on UDT", "create AQ from table", or "The `min`,`max`,`avg`,`sum` aggregate functions for `sometype` using ODCI" |
| experimental | exactly what it says.  Generators that are not yet "prime time" |

Thoughts?

MK

**Comment by PhilippSalvisberg** [comment]
Right now I think it's the best, that every developer starts with his own generator library project. If it is just a single generator, then the project structure is for sure different compared to a full-blown library with a functionality such as the (no longer available) Quest Codegen Utility. The code of these projects may be hosted on GitHub, BitBucket or somewhere else. It doesn't really matter.

What matters is a Generator Repository. Something similar like an AppStore but specialised for oddgen generators. Developer could provide their ready-to-use generators in that AppStore with some description, categorisation, examples, pictures, etc. oddgen Users could browse/search the AppStore and download install the generators. Like in other AppStores, user may rate and review the generators and rate how helpful reviews are. I understand that Steven had something similar in mind when he wrote the introduction on the [Working Group Template Repository](https://community.oracle.com/docs/DOC-920429) document. Since you have the lead of the working group you experienced that it is a bit difficult to get the project forward when there are almost no generators available. However, I currently see no reason why such an AppStore couldn't be written in APEX, as long as Oracle is going to offer free hosting ;-).

I'd like to create a git repository for a project or a set of artefacts which are released together. The current "oddgen" repository releases a SQL Developer Extension. Therefore it should be renamed to "sqldev". This would make things clearer, especially when we get a "plsqldev" plugin in the future. The oddgen AppStore application will have independent release cycle and should therefore get a own git repository. And your library of database server generators could be named "dbgenlib" and should be managed in a dedicated git repository as well.

I suggest that you create an empty GitHub repository and start contributing the generators exactly in the structure you described above. And if you like we could discuss moving this repository to the oddgen organisation once it is populated.

So these are my thoughts so far. 

@stevenfeuerstein and @pepwork : what are your thoughts?

**Comment by MikeKutz** [comment]
PERL and R have their own "appstore" called CPAN and CRAN.

As such, oddgen templates could be fetched via CTAN. (horrible name, I need suggestions)

Should the application that the end-user uses be in a 3rd repository?
I'm thinking "yes".

MK

**Comment by MikeKutz** [comment]
Brain is working too feverishly on this.

Please take a look at this and leave comments.
https://github.com/MikeKutz/templates/tree/initial-load

I want to get the required XSD files "just right" but need some comments regarding the overall layout.

Many thanks for you input,

MK

**Comment by PhilippSalvisberg** [comment]
Creating dedicated Git repositories for generators is the way to go.
