### ISSUE TITLE
Would a "GetInterfaces()" function be beneficial?

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#35]
The interfaces for the generators are naturally evolving.

Although one can query the database for "which interfaces have been implemented?" (and "which version it is?"), it might make sense to have an optional interface to handle that specific job.

This would allow (advanced) developers to tell oddgen what it has.

This concept comes from my experience using other APIs
eg
https://docs.oracle.com/cd/B28359_01/appdev.111/b28425/ext_idx_ref.htm#BJEJEIJD
ODCIGetInterfaces() describes if the Extnsible Index is using 8i interfaces or current version.

My $0.02

MK

**Comment by PhilippSalvisberg** [comment]
No, I do not see a value in this feature, since the extension is capable to identify the relevant version without an explicit list of implemented interfaces.

For generators implementing a PL/SQL interface we identify the implemented functions by signature. A version would make sense for functions with the same signature but different behaviour. However, I try to avoid this situation by design and might name such functions differently. Regarding the Java interface the designer defines which interface(s) he implements. I plan to add a version number to the interface so I may steer the behaviour within oddgen.
