### ISSUE TITLE
Ubuntu installation woes

### ISSUE THREAD

**Issue by tschf** [oddgen/oddgen#38]
I tried to install this a while back but didn't get anywhere, thought I'd revisit. 

I'm on SQL Dev version 4.1.3, and my system is Ubuntu Linux (16.04 x64). I don't have any other extensions installed and am not overly familiar with the SQL Dev extension system. Anyhow, I saw the linked post about OS X issues, which kind of pointed me in the right direction. I had the file `/tmp/$USER/jdeveloper-deferred-updates.txt`. This contained one line, pointing to `/home/$USER/.sqldeveloper/jdeveloper-deferred-updates.txt`. It's content was:

```
temp=/home/trent/.sqldeveloper/tmp/update
globalExtensionsHome=/opt/sqldeveloper/sqldeveloper/extensions
patchesHome=/opt/sqldeveloper/sqldeveloper/lib//patches
userExtensionsHome=/home/trent/.sqldeveloper/extensions
globalSettingsHome=/opt/sqldeveloper/sqldeveloper/lib/
userSettingsHome=/home/trent/.sqldeveloper//lib
oracleHome=/opt/sqldeveloper/
bundlesInfoHome=/opt/sqldeveloper/configuration
InstallExtensionTask=/home/trent/Downloads/oddgen_for_SQLDev_0.2.3.zip,/opt/sqldeveloper/sqldeveloper/extensions,false,org.oddgen.sqldev
UpdateExtraInfo=org.oddgen.sqldev,EXTENSION,,0.2.3.20160624.010216,oddgen for SQL Developer,,Other,SQL Developer extension to invoke dictionary driven code generators.,Philipp Salvisberg,https://www.oddgen.org/,oddgen for SQL Developer
```

I dont think thats anything meaningful. If I launch SQL Dev from the launcher, after trying to install the extension and it requesting a restart, SQL Dev stays closed. I then launch from the console to see what output I get. I get the following:

```
trent@birroth:~/.sqldeveloper$ sqldeveloper 

 Oracle SQL Developer
 Copyright (c) 1997, 2015, Oracle and/or its affiliates. All rights reserved.

Installing updates...
Failed to create file /opt/sqldeveloper/sqldeveloper/extensions/org.oddgen.sqldev.jar.
Permission denied
Update installation failed.
```

So, it's quite apparent my user doesn't have permission to write to /opt/sqldeveloper.

So, next I tried installing as `sudo`. This works and the generator option appears in the `View` menu (As root). If I relaunch on my account, the Generator menu item is not there (so I suppose the installation installs both that jar file and files in the ~/.sqldeveloper dir). 

Beyond changing the folder permissions of /opt/sqldeveloper, or running as root, both of which I'm not keen on, not sure best way to proceed. Do you have any tips? :)

**Comment by tschf** [comment]
Looking at that file `/home/$USER/.sqldeveloper/jdeveloper-deferred-updates.txt`, I noticed:
- globalExtensionsHome=/opt/sqldeveloper/sqldeveloper/extensions
- userExtensionsHome=/home/trent/.sqldeveloper/extensions

So, I tried modifying the InstallExtensionTask to point to userExtensionsHome instead of globalExtensionsHome, to see what would happen - but this just led to:

```
Installing updates...
Failed to write /opt/sqldeveloper/configuration/updates/org.oddgen.sqldev.installinfo.
/opt/sqldeveloper/configuration/updates/org.oddgen.sqldev.installinfo (Permission denied)
Update installation failed.
```

**Comment by PhilippSalvisberg** [comment]
I have to try it in a Linux system first... However, I guess that installing the extension as root is ok, but you probably have to change the permissions of the org.oddgen.sqldev.jar file manually to make it readable for other users.

**Comment by PhilippSalvisberg** [comment]
I cannot reproduce the issue on CentOS 7. 

To successfully install SQL Developer and the oddgen extension I've done the following:
1. download version 4.1.3.20.78,  [Linux RPM](http://www.oracle.com/technetwork/developer-tools/sql-developer/downloads/index.html)
2. opened a terminal window
3. installed Java 8 SDK with `sudo yum install java-1.8.0-openjdk-devel.x86_64`
4. installed SQL Developer with `sudo rpm -i sqldeveloper-4.1.3.20.78-1.noarch.rpm`
5. changed directory with `cd /opt/sqldeveloper`
6. started SQL Developer as root with `sudo ./sqldeveloper.sh` when asked for the full pathname of a JDK installation I've entered `/etc/alternatives/java_sdk_1.8.0`
7. Installed [oddgen via update center](https://www.oddgen.org/download#installation_via_update_center)
8. restarted SQL Developer (still as root)
9. exited SQL Developer
10. started SQL Developer as my user with `./sqldeveloper.sh` when asked for the full pathname of a JDK installation (again) I've entered `/etc/alternatives/java_sdk_1.8.0` (again)

I've tried that with other SQL Developer extensions as well and it worked. 

BTW: You should not need to change the content of `jdeveloper-deferred-updates.txt`. This file is used by the update process internally. On my blog post [Cannot Install Extensions in SQL Developer 4 on Mac OS X](https://www.salvis.com/blog/2015/05/05/cannot-install-extensions-in-sql-developer-4-on-mac-os-x/) I describe a case where the installation process fails due to a name conflict which prohibits to copy this file to the foreseen temporary location. But the problem you are describing is similar to the problems Windows users have if they install SQL Developer in C:\Program Files. See also [I cannot install any extension on Windows](https://www.salvis.com/blog/faq/i-cannot-install-any-extension-on-windows/).

**Comment by tschf** [comment]
Hmm, ok. Ubuntu is a Debian based distro, and uses `deb`s instead of `rpm`s. I installed with `alien` by converting the rpm to a deb before installing. (CentOS is Red Hat based)

My`~/.sqldeveloper/4.1.0/product.conf` points to the JDK: `SetJavaHome /usr/lib/jvm/java-8-openjdk-amd64/` , though I don't think that has a bearing on this issue. 

Java version:

```
$ apt-cache policy openjdk-8-jdk
openjdk-8-jdk:
  Installed: 8u91-b14-3ubuntu1~16.04.1
  Candidate: 8u91-b14-3ubuntu1~16.04.1
  Version table:
 *** 8u91-b14-3ubuntu1~16.04.1 500
        500 http://au.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     8u77-b03-3ubuntu3 500
        500 http://au.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```

I was installing through the local file method. Just tried through the update centre as you did - still oddgen isn't in the menu after launching SQL Developer as my user.

Also, I realise that file isn't meant to be edited - was just trying to find a way to get it to install.

**Comment by PhilippSalvisberg** [comment]
ok... I'm setting up an Ubuntu VM...

**Comment by tschf** [comment]
No probs. For what its worth, the method (from memory) I use to install is:

```
sudo apt-get install openjdk-8-jdk
sudo apt-get install alien
sudo alien --to-deb -c <sqldev-file.rpm>
```

This will have generated the deb file (it does take a few minutes). Here you can either install with `sudo dpkg -i <sqldev.deb>` or through the GUI. I used the GUI.

**Comment by PhilippSalvisberg** [comment]
Thanks. I'll try. Upgrade from Ubuntu 14.04 to 16.04 is running...

**Comment by PhilippSalvisberg** [comment]
Upgrade to Ubuntu 16.04 failed. Does not work within Parallels 11, even if the support pages says different, most probably the problems are caused by Parallels Tools and not by Ubuntu. 

However, so I tried it with Ubuntu 14.04 and I hope that it behaves in this area similar enough.

#### To Reproduce
1. Installed Java 8
   - `sudo apt-add-repository ppa:webupd8team/java`
   - `sudo apt-get update`
   - `sudo apt-get install oracle-java8-installer`
2. Converted RPM package
   - `sudo alien --scripts --to-deb sqldeveloper-4.1.3.20.78-1.noarch.rpm` (not really fast)
3. Installed SQL Developer
   - `sudo dpkg -i sqldeveloper_4.1.3.20.78-2_all.deb` 
4. changed directory with `cd /opt/sqldeveloper`
5. started SQL Developer as root with `sudo ./sqldeveloper.sh` when asked for the full pathname of a JDK installation I've entered `/usr/lib/jvm/java-8-oracle`
6. Installed [oddgen via update center](https://www.oddgen.org/download#installation_via_update_center)
7. restarted SQL Developer (still as root), oddgen Extension was available
8. exited SQL Developer
9. Start SQL Developer as my user with `./sqldeveloper.sh`, **but this failed without error message**.

#### To Fix
1. Deleted $HOME/.sqldeveloper with `sudo rm -r $HOME/.sqldeveloper`
2. Started SQL Developer as my user again with `/opt/sqldeveloper/sqldeveoper.sh` and when asked for the full pathname of a JDK installation I've entered `/usr/lib/jvm/java-8-oracle`

Afterwards I could configure new connections and the oddgen extension was working.

So I assume the ownership and the access rights of $HOME/.sqldeveloper and its content were wrong. Deleting the directory was a bit extreme, using `chmod -R 777` or `chown -R` might be sufficient.

**Comment by PhilippSalvisberg** [comment]
@tschf I could fully reproduce your problem on a fresh Ubuntu 16.04 installation (which works within Parallels - just the Update from 14.04 to 16.04 was not working). 

#### To Reproduce
1. Install Java 8
2. Install SQL Developer
3. Start SQL Developer als normal user with `sqldeveloper` and install oddgen
4. Restart SQL Developer (oddgen is not completely installed, error on copying the org.oddgen.sqldev.jar)
5. Restart SQL Developer with `sudo sqldeveloper`
6. Install oddgen from file (not possible via update site since oddgen is registered as installed)
7. Restart SQL Developer (still as root), oddgen is fully installed
8. Restart SQL Developer as normal user with `sqldeveloper` and "Generators" is not visible in the Views menu

#### To Fix
1. open a terminal
2. enter `sudo rm -r $HOME/.sqldeveloper/system4.1.3.20.78/system_cache`
3. Restart SQL Developer as normal user and "Generators" is visible.

HTH

**Comment by tschf** [comment]
Good stuff, that worked :+1:
