### ISSUE TITLE
Data from Clipboard?

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#56]
This is coming from Oracle Forums ( https://community.oracle.com/thread/4345064 )

Can we use the data from the Clipboard?
If so, how?  (I thought this was implemented and I just forgot how.  But, I'm probably wrong. )

In this case, an eXtend generator should probably be used to transform the Shift-CTRL-C copy of the table results into a `WHERE` clause.

**Comment by PhilippSalvisberg** [comment]
>Can we use the data from the Clipboard?
If so, how? (I thought this was implemented and I just forgot how. But, I'm probably wrong. )

Open the generator dialog and paste the clipboard content into the input parameter of your choice

You do not need a Java generator for that. It's possible with PL/SQL. However, the problem is that oddgen does not support multiline input parameters and therefore all line breaks are lost. Nonetheless, this example gives you an idea. The result could be generated to the clipboard and pasted to the target position.

``` sql
CREATE OR REPLACE PACKAGE in_clause AS
   FUNCTION generate (
      in_node IN oddgen_types.r_node_type
   ) RETURN CLOB;
   --
   FUNCTION get_nodes (
      in_parent_node_id IN oddgen_types.key_type DEFAULT NULL
   ) RETURN oddgen_types.t_node_type;
   --
   FUNCTION get_name RETURN VARCHAR2;
   --
   FUNCTION get_description RETURN VARCHAR2;
END;
/
CREATE OR REPLACE PACKAGE BODY in_clause AS
   FUNCTION generate (
      in_node IN oddgen_types.r_node_type
   ) RETURN CLOB IS
   BEGIN
      RETURN in_node.params('Input');
   END;
   --
   FUNCTION get_nodes (
      in_parent_node_id IN oddgen_types.key_type DEFAULT NULL
   ) RETURN oddgen_types.t_node_type IS
      r_node oddgen_types.r_node_type;
   BEGIN
      r_node.id              := 'Pseudo';
      r_node.name            := 'Generator Input';
      r_node.params('Input') := 'empno' || chr(9) || 'ename' || chr(10) 
                             || '7369'  || chr(9) || 'SMITH' || chr(10)
                             || '7499'  || chr(9) || 'ALLEN' || chr(10);
      r_node.leaf            := true;
      r_node.generatable     := true;
      RETURN oddgen_types.t_node_type(r_node);
   END;
   --
   FUNCTION get_name RETURN VARCHAR2 IS
   BEGIN
      RETURN 'In Clause';
   END;
   -- 
   FUNCTION get_description RETURN VARCHAR2 IS
   BEGIN
      RETURN 'Paste clipboard content of shift-ctrl-c of a table grid into the input field.';
   END;
END;
/
```

With the current version of oddgen it is not possible to implement the requirement defined in https://community.oracle.com/thread/4345064
