### ISSUE TITLE
Extend oddgen interface to support sort order of parameters

### ISSUE THREAD

**Issue by PhilippSalvisberg** [oddgen/oddgen#7]
The sort order of the custom parameters as used in [plsql_view package body](https://github.com/oddgen/oddgen/blob/master/examples/package/plsql/plsql_view.pkb) cannot be influenced by the generator designer, since the underlying Java HashMap leads to a random sort order (original sort order is lost after the conversion from the associative PL/SQL array).

The associative PL/SQL array is ordered by name. This means that technically the ordering is definable within the current oddgen interface, e.g. by using a number as prefix for parameters. But nonetheless an explicit mechanism should be provided.

**Comment by MikeKutz** [comment]
Data encoded strings are always a "bad idea" (eg having the "parameter name" include a value so that you can sort on it)

There is a lot more to developing a GUI for parameters than just retrieving a simple KEY-VALUE pair from the database.
Take a look at all of the metadata available for an APEX Item to see what can be needed.

Best examples:
- Required Parameter
- Tool tip
- Linked Lists (LOV of one parameter is based on current value of another LOV)

As such, you may want to consider returning a single XML value instead of an aa.

Doing this might help with keeping database logic (list of parameters) separate from GUI logic (how to display them)
This might even help other GUIs (APEX, PL/SQL Developer) to reuse the same GUI logic.
